---
name: Publishing images to GitHub Packages

on:
  workflow_dispatch:
  push:
    tags:
      - 'latest'
      - 'v*.*.*'
    schedule:
      - cron: '0 0 1 */1 *'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        container: [ethsecurity]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract the metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.actor }}/${{ matrix.container }}
          tags: |
            type=schedule,pattern=nightly
            type=schedule,pattern={{date 'YYYY-MM'}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{raw}}
            type=match,pattern=latest,group=0

      - name: Build and push the image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.container }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ github.actor }}/${{ matrix.container }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
