---
name: Publishing images to Docker Hub

on:
  workflow_dispatch:
  push:
    tags:
      - 'latest'
      - 'v*.*.*'
    schedule:
      - cron: '0 0 1 */1 *'

jobs:
  buildx-and-push:
    strategy:
      matrix:
        container: [ethsecurity]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract the metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.container }}
          tags: |
            type=schedule,pattern=nightly
            type=schedule,pattern={{date 'YYYY-MM'}}
            type=semver,pattern=v{{major}}
            type=semver,pattern={{raw}}
            type=match,pattern=latest,group=0

      - name: Build and push the image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.container }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64